



spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/orm?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**
  http:
      multipart:
        max-file-size: 4Mb
        max-request-size: 10Mb # 最大支持请求大小



beetlsql:
  basePackage: com.yhshao.springboot.dao
  nameConversion: org.beetl.sql.core.DefaultNameConversion

beetl-beetlsql:
  dev: true






beetl:
  suffix: html btl
  templatesPath: /templates
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false


#logging:
#  file: my.log
#  path: /log
#  level:
#    root: info
#    org: warn
#    com:
#      yhshao: debug
