



spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/orm?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456




beetlsql:
  basePackage: com.yhshao.springboot.dao
beetl-beetlsql:
  dev: true


logging:
  file: my.log
  path: /log
  level:
    root: info
    org: warn
    com:
      yhshao: debug